apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-deployment
    labels:
        app: gonk
spec:
    replicas: {{ .Values.replicaCount}}
    selector:
        matchLabels:
            app: gonk
    template:
        metadata:
            labels:
                app: gonk
        spec:
            containers:
                - name: {{ .Release.Name }}
                  image: brandonlbarrow/gonk:latest
                  env:
                      - name: PATH
                        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                      - name: DISCORD_STREAM_CHANNEL_ID
                        value: {{ quote .Values.discord.streamChannelID }}
                      - name: DISCORD_BOT_TOKEN
                        valueFrom:
                            secretKeyRef:
                                name: gonk
                                key: TOKEN
                      - name: DISCORD_GUILD_ID
                        value: {{ quote .Values.discord.guildID }}
                      - name: DISCORD_USER_ID
                        value: {{ quote .Values.discord.userID }}
                      - name: DISCORDGO_LOG_LEVEL
                        value: {{ .Values.discord.discordgoLogLevel }}
                      - name: GONK_LOG_LEVEL
                        value: {{ .Values.discord.logLevel }}
                      - name: VERSION
                        value: {{ .Chart.AppVersion }}
                      - name: TCDB_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: gonk
                                key: TCDB_API_KEY
