apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-deployment
    labels:
        app: gonk
spec:
    replicas: {{ .Values.replicaCount}}
    selector:
        matchLabels:
            app: gonk
    template:
        metadata:
            labels:
                app: gonk
        spec:
            containers:
                - name: {{ .Release.Name }}
                  image: {{ .Values.image }}
                  env:
                      - name: PATH
                        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                      - name: STREAM_CHANNEL
                        valueFrom:
                            secretKeyRef:
                                name: gonk
                                key: STREAM_CHANNEL
                      - name: TOKEN
                        valueFrom:
                            secretKeyRef:
                                name: gonk
                                key: TOKEN
                      - name: GUILD_ID
                        valueFrom:
                            secretKeyRef:
                                name: gonk
                                key: GUILD_ID
                      - name: TCDB_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: gonk
                                key: TCDB_API_KEY
