name: docker-build-and-push
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: brandonlbarrow/gonk:latest
          secrets: |
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
            STREAM_CHANNEL=${{ secrets.STREAM_CHANNEL }}
            GUILD_ID=${{ secrets.GUILD_ID }}

    
